# Telegram Channel Multiplexer configuration file
# Provide chat IDs as integers. Use negative IDs for supergroups/channels as required by Telegram.
bot_token: <TELEGRAM_BOT_TOKEN>

# Chats where the bot listens for new content to forward.
source_chats:
  - -1001111111111
  - -1002222222222

# Chats where messages should be forwarded. Optional thread IDs route messages into forum topics.
target_chats:
  - chat_id: -1003333333333
  - chat_id: -1004444444444
    thread_id: 5678

# Telegram usernames (without the leading @) allowed to administer the bot.
admin_usernames:
  - primaryadmin
  - backupadmin

# Delay in seconds between forwarding consecutive messages.
delay_seconds: 1.5
